server:
  port: 9002
spring:
  application:
    name: spring-gateway
  cloud:
    gateway:
      routes:
        - id: consumer
          uri: lb://spring-cloud-consumer
          predicates:
          - Path=/consumer/**
          filters:
          - StripPrefix=1
        - id: producer
          uri: lb://spring-cloud-producer
          predicates:
          - Path=/producer/**
          filters:
          - StripPrefix=1
        - id: auth
          uri: lb://spring-cloud-auth
          predicates:
          - Path=/auth/**
          filters:
          - StripPrefix=1
#用url定义        - id: my_route
        #          uri: http://www.ityouknow.com
        #          predicates:
        #          - Path=/spring-cloud
        #          filters:
        #          - StripPrefix=1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/